version: '3.8'
services:
  mysql:
    image: mysql:8
    container_name: cartegrise-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cartegrise
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d
volumes:
  mysql_data: