CREATE DATABASE IF NOT EXISTS cartegrise;
USE cartegrise;

CREATE TABLE IF NOT EXISTS users (
	id VARCHAR(36) PRIMARY KEY,
	email VARCHAR(255) UNIQUE NOT NULL,
	password VARCHAR(255) NOT NULL,
	first_name VARCHAR(100) NOT NULL,
	last_name VARCHAR(100) NOT NULL,
	phone VARCHAR(20) NULL,
	address VARCHAR(255) NULL,
	role VARCHAR(20) NOT NULL DEFAULT 'user',
	email_verified TINYINT(1) NOT NULL DEFAULT 0,
	verification_token VARCHAR(255) NULL,
	reset_token VARCHAR(255) NULL,
	reset_token_expires_at DATETIME NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS dossiers (
	id VARCHAR(36) PRIMARY KEY,
	numero VARCHAR(50) UNIQUE NOT NULL,
	user_id VARCHAR(36) NOT NULL,
	type_demande VARCHAR(50) NOT NULL,
	statut VARCHAR(50) NOT NULL DEFAULT 'brouillon',
	prix_total DECIMAL(10,2) NOT NULL DEFAULT 0,
	current_step INT NOT NULL DEFAULT 1,
	form_data JSON NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT fk_dossiers_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS vehicles (
	id VARCHAR(36) PRIMARY KEY,
	dossier_id VARCHAR(36) NOT NULL,
	immatriculation VARCHAR(20) NOT NULL,
	marque VARCHAR(100) NULL,
	modele VARCHAR(100) NULL,
	puissance_fiscale INT NULL,
	energie VARCHAR(50) NULL,
	annee INT NULL,
	CONSTRAINT fk_vehicles_dossier FOREIGN KEY (dossier_id) REFERENCES dossiers(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS documents (
	id VARCHAR(36) PRIMARY KEY,
	dossier_id VARCHAR(36) NOT NULL,
	type VARCHAR(50) NOT NULL,
	url VARCHAR(500) NOT NULL,
	filename VARCHAR(255) NOT NULL,
	size INT NOT NULL,
	verified TINYINT(1) NOT NULL DEFAULT 0,
	uploaded_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT fk_documents_dossier FOREIGN KEY (dossier_id) REFERENCES dossiers(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS payments (
	id VARCHAR(36) PRIMARY KEY,
	dossier_id VARCHAR(36) NOT NULL,
	montant DECIMAL(10,2) NOT NULL,
	statut VARCHAR(20) NOT NULL DEFAULT 'en_attente',
	stripe_session_id VARCHAR(255) NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT fk_payments_dossier FOREIGN KEY (dossier_id) REFERENCES dossiers(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS audit_logs (
	id VARCHAR(36) PRIMARY KEY,
	actor_user_id VARCHAR(36) NULL,
	action VARCHAR(255) NOT NULL,
	resource_type VARCHAR(100) NULL,
	resource_id VARCHAR(100) NULL,
	details JSON NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);